# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fai < Formula
  desc "CLI for the fromai coding task manager"
  homepage "https://github.com/ktappdev/fromai.dev"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ktappdev/fromai.dev/releases/download/v1.0.0/fromai.dev_1.0.0_darwin_amd64.tar.gz"
      sha256 "cff29e75622c504fb78e1468b635803d7681e4dcd02c60e00e657c209bdf5af1"

      define_method(:install) do
        bin.install "fai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ktappdev/fromai.dev/releases/download/v1.0.0/fromai.dev_1.0.0_darwin_arm64.tar.gz"
      sha256 "4f04386c7950c31300137fa0edf221497a9787988901e906a6fab28b9c5cea39"

      define_method(:install) do
        bin.install "fai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ktappdev/fromai.dev/releases/download/v1.0.0/fromai.dev_1.0.0_linux_amd64.tar.gz"
      sha256 "6a3ba25075441be4fd3c1ee541fddadd7996daf3510de342749c7032a75d65c9"
      define_method(:install) do
        bin.install "fai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ktappdev/fromai.dev/releases/download/v1.0.0/fromai.dev_1.0.0_linux_arm64.tar.gz"
      sha256 "5d6853d0deccebeeab3ec775dece5ba4e00f7120e1d86f4c46964718629de9ab"
      define_method(:install) do
        bin.install "fai"
      end
    end
  end

  test do
    system "#{bin}/fai --help"
  end
end
