# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fai < Formula
  desc "CLI for the fromai coding task manager"
  homepage "https://github.com/ktappdev/fromai"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ktappdev/fromai/releases/download/v1.1.0/fromai_1.1.0_darwin_amd64.tar.gz"
      sha256 "ce931a52c8e318ee2bb287dc5119d1e7c90f93bbd5d5f805bdbc757f46194b8f"

      define_method(:install) do
        bin.install "fai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ktappdev/fromai/releases/download/v1.1.0/fromai_1.1.0_darwin_arm64.tar.gz"
      sha256 "a4d2d09bf8070f6226db005e34aedd141ef276f5f193267778f1f473184056bc"

      define_method(:install) do
        bin.install "fai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ktappdev/fromai/releases/download/v1.1.0/fromai_1.1.0_linux_amd64.tar.gz"
      sha256 "bd1983d0b6aa34f03b7f1e9eafd07e2d2aa9928d87a5662198590d1d7ed902af"
      define_method(:install) do
        bin.install "fai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ktappdev/fromai/releases/download/v1.1.0/fromai_1.1.0_linux_arm64.tar.gz"
      sha256 "430e3548f1ff39e936c4900a5ecb4165e375dca897e228af31f53f99e266d343"
      define_method(:install) do
        bin.install "fai"
      end
    end
  end

  test do
    system "#{bin}/fai --help"
  end
end
